{{- if .Values.efs }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.efs.name }}
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
mountOptions:
  - tls
  - iam
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.efs.name }}
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  mountOptions:
    - tls
    - iam
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.efs.name }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.id }}::{{ .Values.efs.accessPoint }}
    volumeAttributes:
        encryptInTransit: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.efs.name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.efs.name }}
---
{{- end }}