apiVersion: v1
kind: ServiceAccount
metadata:
  name: agency-server
  labels:
    group: cryptoexchange
    app: agency-server
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
