package com.crypto.exchange.caas.service.order;

public enum InboundEventType {
  // Market Data Event
  BOOK,
  BOOK_FEED_STATUS,
  TRADE,
  TRADE_FEED_STATUS,
  STATISTICS,
  STATISTICS_FEED_STATUS,

  // Parent Order Event
  NEW_PARENT_ORDER,
  CANCEL_PARENT_ORDER,
  PAUSE_PARENT_ORDER,
  RESUME_PARENT_ORDER,

  // Child Order Event
  NEW_CHILD_ORDER_ACK,
  NEW_CHILD_ORDER_REJECT,
  CANCEL_CHILD_ORDER_ACK,
  CANCEL_CHILD_ORDER_REJECT,
  CHILD_ORDER_FULLY_FILLED,
  CHILD_ORDER_PARTIALLY_FILLED,
  CHILD_ORDER_UNSOLICITED_CANCEL,

  // TIMER
  TIMER,

  // Recovery
  PARENT_ORDER_RECOVERY,
  CHILD_ORDER_RECOVERY,
  RECOVERY_END
}
