package com.crypto.exchange.caas.service.order;

public enum OutboundEventType {
  // Parent Order Event
  NEW_PARENT_ORDER_ACK,
  NEW_PARENT_ORDER_REJECT,
  CANCEL_PARENT_ORDER_ACK,
  CANCEL_PARENT_ORDER_REJECT,
  UNSOLICITED_CANCEL_PARENT_ORDER,
  PARENT_ORDER_FILLED,
  PARENT_ORDER_PAUSED,
  PARENT_ORDER_RESUMED,

  // Child Order Event
  NEW_CHILD_ORDER,
  CANCEL_CHILD_ORDER,
  FORCE_CANCEL_CHILD_ORDER
}
